# Generated by Django 4.2.4 on 2023-08-24 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartmodel',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, to='cart.cartitemmodel'),
        ),
    ]
