# Generated by Django 4.2.4 on 2023-08-24 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cartmodel_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartmodel',
            old_name='products',
            new_name='cart_items',
        ),
    ]
